version: '3.7'

services:

  wordpress:
    build:
      context: ./wordpress
    links:
      - server
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: asmp
      ASMP_DISCOVERY_VERSION: v1
      ASMP_DISCOVERY_ENDPOINT: http://server:8080
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins

  server:
    build:
      context: ./server
    command: bash -c "cd /var/www/html && git pull && composer install && php src/main.php"
    ports:
      - 5000:8080

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: asmp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root